FROM node:lts as build-stage
WORKDIR /app
RUN npm install -g @ionic/cli
COPY package*.json ./
RUN npm install
COPY ./ .
ENV API_URL http://35.232.171.18:8000
ENV PRODUCTION true
RUN npm run config-ts
RUN ionic build --engine=browser

FROM nginx:alpine as production-stage
RUN mkdir /app
COPY --from=build-stage /app/www /app
COPY nginx.conf /etc/nginx/nginx.conf