FROM node:lts
WORKDIR /app
RUN npm install -g @ionic/cli
ENV API_URL http://35.232.171.18:3000
ENV PRODUCTION true
RUN npm run config-ts
RUN ionic build --engine=browser

FROM nginx:alpine as production-stage
RUN mkdir /app
COPY --from=build-stage /app/www /app
COPY nginx.conf /etc/nginx/nginx.conf