services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    working_dir: /home/node/app
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./frontend:/home/node/app
  backend:
    build: ./backend
    ports:
      - 8000:3000
    working_dir: /home/node/app
    env_file:
      - .env
    volumes:
      - ./backend:/home/node/app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: