services:
  frontend:
    image: node:lts
    ports:
      - 8000:3000
    command: sh -c "npm install && npm install -g @angular/cli && ng serve --host=0.0.0.0 --port 3000"
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
  backend:
    image: node:lts
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run start:dev"
    working_dir: /home/node/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=database
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
    env_file:
      - .env
    volumes:
      - ./backend:/home/node/app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: