services:
  frontend:
    build: ./frontend
    command: sh -c "npm install && ionic serve --external"
    ports:
      - 8100:8100
      - 35729:35729
      - 53703:53703
    working_dir: /home/node/app
    env_file:
      - .env
    volumes:
      - ./frontend:/home/node/app
  backend:
    image: node:lts
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run start:dev"
    working_dir: /home/node/app
    env_file:
      - .env
    volumes:
      - ./backend:/home/node/app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: